apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
spec:
  replicas: 2 # Number of pods
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
        - name: k8s-test-app
          image: k8s-test-app:latest
          imagePullPolicy: Never # Tell Kubernetes not to pull from a registry
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app
spec:
  selector:
    app: k8s-test-app
  ports:
    - port: 8080
      targetPort: 8080
